// This file is auto generated by msgidgen, DO NOT EDIT!!
package coredef
import (
	"github.com/golang/protobuf/proto"
	"log"
	"core/netdef"
	"core/pbcodec"
)

func MsgAdapter_RemoteCallREQ(pkt *netdef.Packet,c netdef.IPacketContext) {

	msg := &RemoteCallREQ{}

	err := proto.Unmarshal(pkt.Data, msg)

	if err != nil {
		log.Printf("[RemoteCallREQ] unmarshaling error:\n", err)
		return
	}

	c.Map(msg)
}

func MsgAdapter_RemoteCallACK(pkt *netdef.Packet,c netdef.IPacketContext) {

	msg := &RemoteCallACK{}

	err := proto.Unmarshal(pkt.Data, msg)

	if err != nil {
		log.Printf("[RemoteCallACK] unmarshaling error:\n", err)
		return
	}

	c.Map(msg)
}

func MsgAdapter_RPCEchoACK(pkt *netdef.Packet,c netdef.IPacketContext) {

	msg := &RPCEchoACK{}

	err := proto.Unmarshal(pkt.Data, msg)

	if err != nil {
		log.Printf("[RPCEchoACK] unmarshaling error:\n", err)
		return
	}

	c.Map(msg)
}

func MsgAdapter_RelayMessageACK(pkt *netdef.Packet,c netdef.IPacketContext) {

	msg := &RelayMessageACK{}

	err := proto.Unmarshal(pkt.Data, msg)

	if err != nil {
		log.Printf("[RelayMessageACK] unmarshaling error:\n", err)
		return
	}

	c.Map(msg)
}

func init() {
	pbcodec.RegisterProto("coredef.RemoteCallREQ", 0x8877df13, MsgAdapter_RemoteCallREQ )
	pbcodec.RegisterProto("coredef.RemoteCallACK", 0xe32d2371, MsgAdapter_RemoteCallACK )
	pbcodec.RegisterProto("coredef.RPCEchoACK", 0x571e8c6e, MsgAdapter_RPCEchoACK )
	pbcodec.RegisterProto("coredef.RelayMessageACK", 0xfd09a2c9, MsgAdapter_RelayMessageACK )
}